### ISSUE TITLE
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:     1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

### ISSUE THREAD

**Issue by TIMESTICKING** [cvzone/cvzone#12]
hi, when im trying Pose Estimation an error occured. says its abt the arguments in "detector = PoseDetector(upBody=1)".
details refer to below:
```
Traceback (most recent call last):
  File "F:/embedding_sys_proj/arduino_files/esp32 cam/rev_imgs_from_esp32cam/eyesteady.py", line 54, in <module>
    detector = PoseDetector(upBody=1)
  File "D:\python37\lib\site-packages\cvzone\PoseModule.py", line 35, in __init__
    self.detectionCon, self.trackCon)
  File "D:\python37\lib\site-packages\mediapipe\python\solutions\pose.py", line 166, in __init__
    outputs=['pose_landmarks', 'pose_world_landmarks', 'segmentation_mask'])
  File "D:\python37\lib\site-packages\mediapipe\python\solution_base.py", line 260, in __init__
    for name, data in (side_inputs or {}).items()
  File "D:\python37\lib\site-packages\mediapipe\python\solution_base.py", line 260, in <dictcomp>
    for name, data in (side_inputs or {}).items()
  File "D:\python37\lib\site-packages\mediapipe\python\solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.5
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
```

is this something wrong abt the version of mediapipe?

**Comment by Vatsa0408** [comment]
@TIMESTICKING , the upBody is not available. It has been removed quite some time ago. 

But i do get the same TypeError.
Here is the traceback log
```
Traceback (most recent call last):
  File "C:\ins\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ins\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\ins\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ins\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ins\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 2096, in <module>
    main()
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 1983, in main
    smooth_lm, enableSegmentation, smoothSegmentation,minDetectCon, minTrackCon)
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 670, in __init__
    self.pose = self.mpPose.Pose(static_image_mode = self.staticMode,model_complexity = self.modelComplexity, smooth_landmarks = self.smooth, enable_segmentation = self.enableSegmentation, smooth_segmentation = self.smoothSegmentation, min_detection_confidence = self.minDetectionCon, min_tracking_confidence = self.minTrackCon)
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solutions\pose.py", line 166, in __init__
    outputs=['pose_landmarks', 'pose_world_landmarks', 'segmentation_mask'])
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 260, in __init__
    for name, data in (side_inputs or {}).items()
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 260, in <dictcomp>
    for name, data in (side_inputs or {}).items()
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 'True'
```
