### ISSUE TITLE
Not able to install cvzone

### ISSUE THREAD

**Issue by Svein-Tore** [cvzone/cvzone#36]
Hi!

I have instaled cvzone and it says it is OK. But when I run the hand program from examples I get the followinmg error:
pi@raspberrypi:~/.local/bin $ python3 handtestcvzone.py
Traceback (most recent call last):
  File "/home/pi/.local/bin/handtestcvzone.py", line 1, in <module>
    from cvzone.HandTrackingModule import HandDetector
  File "/home/pi/.local/lib/python3.9/site-packages/cvzone/HandTrackingModule.py", line 8, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

OK, looks like I have to install mediapipe. I tried:

pip install mediapipe 

but I got the follwoing error:

pi@raspberrypi:~/.local/bin $ pip3 install mediapipe
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

Any suggestions?

**Comment by deseipel** [comment]
I have the same issue

**Comment by youssifashraf** [comment]
i have an issue with installing cvzone 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-994hudmg/opencv-python/

**Comment by vwallajabad** [comment]
Try to update all of the dependency packages it uses. For example cvzone uses opencv and mediapipe so try this ```pip uninstall opencv-python && pip uninstall mediapipe && pip uninstall cvzone``` to uninstall it. Then type ```pip install opencv-python && pip install mediapipe && pip install cvzone ``` to install the latest version. 

If this does not work could you share the python version and OS you are using?

**Comment by aanisar** [comment]
Python 3.9.15
MacOS 12.5.1 on M1 Pro

**Comment by suyashjoshi** [comment]
same here

**Comment by 054saurabh** [comment]
when we run the code i get following error
Traceback (most recent call last):
  File "c:\Users\srbhk\OneDrive\Documents\14.python_core\demo.py", line 2, in <module>
    from cvzone.FaceDetectionModule import FaceDetector
  File "C:\Python310\lib\site-packages\cvzone\FaceDetectionModule.py", line 8, in <module>
    import mediapipe as mp
ModuleNotFoundError: No module named 'mediapipe'

Any suggestions?
