### ISSUE TITLE
mediapipe not working

### ISSUE THREAD

**Issue by klaiv691** [cvzone/cvzone#67]
i have been trying to get rid of this error but it has failed to go away, i need help. "C:\Users\DELL\PycharmProjects\pythonProject3\venv\Scripts\python.exe C:\Users\DELL\PycharmProjects\pythonProject3\check.py 
Traceback (most recent call last):
  File "C:\Users\DELL\PycharmProjects\pythonProject3\check.py", line 2, in <module>
    import mediapipe as mp
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mediapipe\__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed while importing _framework_bindings: The specified module could not be found.

Process finished with exit code 1

**Comment by cvzone** [comment]
Please share the code you are trying to run.

**Comment by klaiv691** [comment]
I was trying to run the face detection example using media pipe as mp

**Comment by klaiv691** [comment]
And then I tried the face detection example that requires using the facedetector module but I got an error message saying that the module isn’t in the cvzone library
